import React, {useCallback, useEffect, useState} from 'react';
import axios from 'axios';
import {Toaster,toast} from 'sonner';
import {AreaChart,Area,BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from 'recharts';
import {Scale,LayoutDashboard,ReceiptText,Users,LogOut,Plus,Printer,Trash2,Download,RefreshCw,ShieldCheck,X,CheckCircle2,Pencil,CalendarX,UserX} from 'lucide-react';
import './App.css';

const API=process.env.REACT_APP_BACKEND_URL;
const api=axios.create({baseURL:API});
const money=n=>`Rp ${(n||0).toLocaleString('id-ID')}`;
const dateId=s=>s?.split('-').reverse().join('/')||'-';
function err(e){const d=e.response?.data?.detail; if(typeof d==='string')return d; if(d?.message)return d.shortage?`${d.message} Target ${d.target.toLocaleString('id-ID')} Kg, maksimum realistis ${d.maximum.toLocaleString('id-ID')} Kg, kurang ${d.shortage.toLocaleString('id-ID')} Kg. ${d.reason}`:d.message; return 'Terjadi kesalahan. Periksa data Anda.'}

function Auth({onLogin}){
 const [mode,setMode]=useState('login'),[form,setForm]=useState({name:'',email:'',password:''});
 const submit=async e=>{e.preventDefault();try{const r=await api.post(`/api/auth/${mode==='login'?'login':'signup'}`,form);if(mode==='login'){localStorage.setItem('sjm_token',r.data.token);api.defaults.headers.common.Authorization=`Bearer ${r.data.token}`;onLogin(r.data.user)}else{toast.success(r.data.message);setMode('login')}}catch(e){toast.error(err(e))}};
 return <><Toaster position="top-right" richColors/><main className="auth-shell"><section className="auth-visual"><div className="brand-mark"><Scale size={28}/></div><p className="eyebrow">PT SAWIT JAYA MAKMUR</p><h1>Penimbangan yang rapi.<br/><em>Keputusan yang pasti.</em></h1><p className="muted-light">Workspace penerimaan buah sawit untuk operasi pengepul yang tertib, realistis, dan siap finance.</p><div className="auth-stamp"><span>07:00—16:00</span><small>JAM PENERIMAAN</small></div></section><section className="auth-panel"><div className="panel-inner"><p className="eyebrow green">SISTEM OPERASIONAL</p><h2>{mode==='login'?'Selamat datang kembali':'Buat akun operator'}</h2><p className="muted">{mode==='login'?'Masuk untuk membuka rekap PT SJM.':'Akun baru akan aktif setelah disetujui admin.'}</p><form onSubmit={submit} data-testid={`${mode}-form`}>{mode==='signup'&&<input data-testid="signup-name-input" required placeholder="Nama lengkap" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input data-testid={`${mode}-email-input`} required type="email" placeholder="Email kerja" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input data-testid={`${mode}-password-input`} required type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button data-testid={`${mode}-submit-button`} className="primary wide">{mode==='login'?'Masuk ke workspace':'Kirim pendaftaran'}</button></form><button className="text-button" data-testid={`switch-to-${mode==='login'?'signup':'login'}-btn`} onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Belum punya akun? Daftar':'Sudah punya akun? Masuk'}</button></div></section></main></>
}

export default function App(){
 const [user,setUser]=useState(null),[ready,setReady]=useState(false),[tab,setTab]=useState('dashboard'),[batch,setBatch]=useState(null),[batches,setBatches]=useState([]),[tx,setTx]=useState([]),[owners,setOwners]=useState([]),[summary,setSummary]=useState(null),[users,setUsers]=useState([]),[modal,setModal]=useState(null),[editTx,setEditTx]=useState(null),[editOwner,setEditOwner]=useState(null),[selected,setSelected]=useState(null),[filters,setFilters]=useState({start:'',end:''});
 useEffect(()=>{const t=localStorage.getItem('sjm_token'); if(t){api.defaults.headers.common.Authorization=`Bearer ${t}`;api.get('/api/auth/me').then(r=>setUser(r.data)).catch(()=>localStorage.removeItem('sjm_token')).finally(()=>setReady(true))}else setReady(true)},[]);
 const load=useCallback(async()=>{if(!user)return;try{const [b,o]=await Promise.all([api.get('/api/batches'),api.get('/api/owners')]);setBatches(b.data);setBatch(x=>x||b.data.find(y=>y.active)?.id||b.data[0]?.id);setOwners(o.data)}catch(e){toast.error('Gagal memuat data master. Periksa koneksi lalu muat ulang.')}},[user]);
 const refresh=useCallback(async()=>{if(!batch)return;try{const [t,s]=await Promise.all([api.get(`/api/transactions?batch_id=${batch}`),api.get(`/api/analytics/summary?batch_id=${batch}${filters.start?`&start=${filters.start}`:''}${filters.end?`&end=${filters.end}`:''}`)]);setTx(t.data);setSummary(s.data)}catch(e){toast.error('Gagal memuat transaksi. Coba lagi.')}},[batch,filters.start,filters.end]);
 useEffect(()=>{load()},[load]); useEffect(()=>{refresh()},[refresh]);
 const loadUsers=useCallback(async()=>{try{setUsers((await api.get('/api/admin/users')).data)}catch(e){toast.error('Gagal memuat daftar akun.')}},[]);
 useEffect(()=>{if(tab==='admin'&&user?.role==='admin')loadUsers()},[tab,user,loadUsers]);
 const logout=()=>{localStorage.removeItem('sjm_token');delete api.defaults.headers.common.Authorization;setUser(null)};
 const createBatch=async month=>{try{const r=await api.post('/api/batches/new',month?{month}:{});toast.success(`Batch ${r.data.label} dimulai dan diaktifkan`);await load();setBatch(r.data.id)}catch(e){toast.error(err(e))}};
 const activateBatch=async id=>{try{await api.post(`/api/batches/${id}/activate`);toast.success('Batch diaktifkan');await load();setBatch(id)}catch(e){toast.error(err(e))}};
 const deleteBatch=async b=>{if(!window.confirm(`Hapus batch ${b.label} beserta SEMUA transaksinya? Tindakan ini tidak bisa dibatalkan.`))return;try{const r=await api.delete(`/api/batches/${b.id}`);toast.success(`Batch dihapus (${r.data.deleted_transactions} transaksi ikut terhapus)`);setBatch(null);await load()}catch(e){toast.error(err(e))}};
 const generate=async e=>{e.preventDefault();try{const f=new FormData(e.currentTarget),r=await api.post('/api/generator/run',{start_date:f.get('start'),end_date:f.get('end'),target_kg:+f.get('target'),price_per_kg:+f.get('price')});toast.success(`Target tepat ${r.data.actual_kg.toLocaleString('id-ID')} Kg dibuat (${r.data.generated_count} transaksi)${r.data.used_lunch_break?' — sebagian melewati jam istirahat':''}`);setModal(null);refresh()}catch(e){toast.error(err(e),{duration:9000})}};
 const remove=async id=>{if(!window.confirm('Hapus transaksi ini?'))return;await api.delete(`/api/transactions/${id}`);toast.success('Transaksi dihapus');refresh()};
 const deleteDay=async d=>{if(!d)return toast.error('Pilih tanggal yang akan dihapus.');if(!window.confirm(`Hapus SEMUA transaksi tanggal ${dateId(d)} pada batch ini?`))return;const r=await api.delete(`/api/transactions/date/${d}?batch_id=${batch}`);toast.success(`${r.data.deleted_count} transaksi tanggal ${dateId(d)} dihapus`);refresh()};
 const approve=async id=>{await api.post(`/api/admin/users/${id}/approve`);toast.success('Akun disetujui');loadUsers()};
 const reject=async id=>{if(!window.confirm('Tolak dan hapus akun ini?'))return;await api.delete(`/api/admin/users/${id}`);toast.success('Akun dihapus');loadUsers()};
 const exportExcel=async()=>{try{const r=await api.get(`/api/export/excel?batch_id=${batch}${filters.start?`&start=${filters.start}`:''}${filters.end?`&end=${filters.end}`:''}`,{responseType:'blob'});const u=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=u;a.download='Rekap_PT_SJM.xlsx';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u);toast.success('Excel finance terunduh')}catch(e){toast.error('Gagal mengunduh Excel')}};
 if(!ready)return <div className="loading">Memuat workspace…</div>; if(!user)return <Auth onLogin={setUser}/>;
 const nav=[['dashboard','Ringkasan',LayoutDashboard],['transactions','Penerimaan',ReceiptText],['owners','Pemilik & Armada',Users],['admin','Approval Admin',ShieldCheck]];
 return <div className="app"><Toaster position="bottom-right" richColors/><aside><div className="side-brand"><div className="brand-mark small"><Scale size={20}/></div><div><b>PT SJM</b><span>SAWIT CONTROL</span></div></div><div className="side-label">WORKSPACE</div>{nav.filter(n=>n[0]!=='admin'||user.role==='admin').map(([id,label,Icon])=><button className={tab===id?'nav active':'nav'} data-testid={`tab-${id}`} onClick={()=>setTab(id)} key={id}><Icon size={17}/>{label}</button>)}<div className="side-bottom"><div className="operator"><div className="avatar">{user.name?.[0]}</div><div><b>{user.name}</b><span>{user.role==='admin'?'ADMIN UTAMA':'OPERATOR'}</span></div></div><button className="nav logout" data-testid="logout-button" onClick={logout}><LogOut size={17}/>Keluar</button></div></aside><main className="content"><header><div><p className="eyebrow green">CONTROL DESK / {batch||'BATCH'}</p><h2>{nav.find(n=>n[0]===tab)?.[1]}</h2></div><div className="header-actions"><select data-testid="batch-selector-dropdown" value={batch||''} onChange={e=>setBatch(e.target.value)}>{batches.map(b=><option key={b.id} value={b.id}>{b.label} {b.active?'· Aktif':'· Arsip'}</option>)}</select><button className="outline" data-testid="manage-batch-button" onClick={()=>setModal('batches')}><RefreshCw size={15}/> Kelola periode</button></div></header>{tab==='dashboard'&&<Dashboard summary={summary} tx={tx} filters={filters} setFilters={setFilters} exportData={exportExcel}/>} {tab==='transactions'&&<Transactions tx={tx} remove={remove} deleteDay={deleteDay} onGenerate={()=>setModal('generate')} onVoucher={setSelected} onEdit={t=>{setEditTx(t);setModal('tx')}} onAdd={()=>{setEditTx(null);setModal('tx')}}/>} {tab==='owners'&&<Owners owners={owners} onEdit={o=>{setEditOwner(o);setModal('owner')}} onAdd={()=>{setEditOwner(null);setModal('owner')}}/>} {tab==='admin'&&<Admin users={users} approve={approve} reject={reject}/>} {modal==='batches'&&<BatchManager batches={batches} isAdmin={user.role==='admin'} onClose={()=>setModal(null)} createBatch={createBatch} activateBatch={activateBatch} deleteBatch={deleteBatch}/>} {modal==='generate'&&<Generate onClose={()=>setModal(null)} submit={generate}/>} {modal==='tx'&&<TxForm batch={batch} owners={owners} initial={editTx} onClose={()=>setModal(null)} refresh={refresh}/>} {modal==='owner'&&<OwnerForm initial={editOwner} onClose={()=>setModal(null)} refresh={load}/>} {selected&&<Voucher tx={selected} onClose={()=>setSelected(null)}/>}</main></div>
}

function Dashboard({summary,tx,filters,setFilters,exportData}){return <section className="page"><div className="filterbar"><div><span className="eyebrow">PERIODE FINANCE</span><b>{filters.start&&filters.end?`${dateId(filters.start)} — ${dateId(filters.end)}`:'Semua transaksi batch'}</b></div><input data-testid="summary-start-date" type="date" value={filters.start} onChange={e=>setFilters({...filters,start:e.target.value})}/><input data-testid="summary-end-date" type="date" value={filters.end} onChange={e=>setFilters({...filters,end:e.target.value})}/><button className="outline" data-testid="export-excel-button" onClick={exportData}><Download size={15}/> Excel</button></div><div className="metrics"><Metric label="NETTO DITERIMA" value={`${(summary?.total_netto_kg||0).toLocaleString('id-ID')} Kg`} tone="green"/><Metric label="TOTAL PEMBELIAN" value={money(summary?.total_spending)} tone="gold"/><Metric label="TRANSAKSI" value={summary?.total_transactions||0} tone="blue"/><Metric label="PEMILIK AKTIF" value={summary?.owner_summary?.length||0} tone="ink"/></div><div className="chart-grid"><div className="section-card chart-card"><div className="section-head"><div><span className="eyebrow">ALIRAN HARIAN</span><h3>Netto masuk per tanggal</h3></div><span className="tag">Kg</span></div><div className="chart">{summary?.daily_summary?.length?<ResponsiveContainer><AreaChart data={[...(summary?.daily_summary||[])].sort((a,b)=>a.label.localeCompare(b.label))}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#159947" stopOpacity=".35"/><stop offset="100%" stopColor="#159947" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e5e9e5"/><XAxis dataKey="label" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip/><Area type="monotone" dataKey="netto_kg" stroke="#159947" fill="url(#fill)" strokeWidth={2}/></AreaChart></ResponsiveContainer>:<div className="empty">Belum ada data untuk periode ini.</div>}</div></div><div className="section-card chart-card"><div className="section-head"><div><span className="eyebrow">KONTRIBUSI PEMILIK</span><h3>Siapa menyumbang paling banyak</h3></div></div><div className="chart">{summary?.owner_summary?.length?<ResponsiveContainer><BarChart data={summary?.owner_summary||[]} layout="vertical"><CartesianGrid horizontal={false} stroke="#e5e9e5"/><XAxis type="number" tick={{fontSize:10}}/><YAxis dataKey="label" type="category" width={75} tick={{fontSize:10}}/><Tooltip/><Bar dataKey="netto_kg" fill="#b97819" radius={[0,3,3,0]}/></BarChart></ResponsiveContainer>:<div className="empty">Belum ada data untuk periode ini.</div>}</div></div></div><div className="section-card"><div className="section-head"><div><span className="eyebrow">REKAP TERBARU</span><h3>Transaksi terakhir</h3></div><span className="muted">{tx.length} baris</span></div><TxTable tx={tx.slice(0,8)}/></div></section>}
function Metric({label,value,tone}){return <div className={`metric ${tone}`}><span>{label}</span><strong data-testid={`metric-${label.toLowerCase().replaceAll(' ','-')}`}>{value}</strong><small>Periode aktif</small></div>}

function TxTable({tx,onVoucher,onEdit,remove}){
 const withActions=onVoucher||onEdit||remove;
 return <div className="table-wrap"><table><thead><tr><th>Kode</th><th>Tanggal</th><th>Pemilik</th><th>Jam</th><th>Gross</th><th>Netto</th><th>Harga/Kg</th><th>Total</th>{withActions&&<th>Aksi</th>}</tr></thead><tbody>{tx.map(t=><tr key={t.id} data-testid={`tx-row-${t.id}`}><td className="mono">{t.transaction_code}</td><td>{dateId(t.date)}</td><td><b>{t.owner_name}</b><small>{t.vehicle_type}</small></td><td className="mono">{t.arrival_time} → {t.exit_time}</td><td>{t.gross_kg.toLocaleString('id-ID')} Kg</td><td className="strong">{t.netto_kg.toLocaleString('id-ID')} Kg<small>{t.netto_ton.toFixed(2)} Ton</small></td><td>{money(t.price_per_kg)}</td><td>{money(t.total_amount)}</td>{withActions&&<td><div className="row-actions"><button title="Voucher" data-testid={`voucher-${t.id}`} className="icon" onClick={()=>onVoucher(t)}><Printer size={15}/></button><button title="Edit" data-testid={`edit-${t.id}`} className="icon" onClick={()=>onEdit(t)}><Pencil size={15}/></button><button title="Hapus" data-testid={`delete-${t.id}`} className="icon danger" onClick={()=>remove(t.id)}><Trash2 size={15}/></button></div></td>}</tr>)}</tbody></table>{!tx.length&&<div className="empty">Belum ada transaksi. Jalankan generator atau catat penerimaan baru.</div>}</div>
}

function Transactions({tx,remove,deleteDay,onGenerate,onVoucher,onEdit,onAdd}){
 const [day,setDay]=useState('');
 return <section className="page"><div className="toolbar"><div><span className="eyebrow">BUKU PENERIMAAN</span><h3>Detail penimbangan</h3></div><div><button className="outline" data-testid="open-generator-button" onClick={onGenerate}><RefreshCw size={15}/> Generate target</button><button className="primary" data-testid="open-add-transaction-button" onClick={onAdd}><Plus size={15}/> Tambah penerimaan</button></div></div><div className="day-delete"><CalendarX size={17}/><div><b>Hapus satu hari penuh</b><p className="muted">Menghapus seluruh transaksi pada tanggal terpilih di batch aktif.</p></div><input data-testid="delete-day-date-input" type="date" value={day} onChange={e=>setDay(e.target.value)}/><button className="danger-outline" data-testid="delete-day-button" onClick={()=>deleteDay(day)}><Trash2 size={14}/> Hapus tanggal ini</button></div><div className="section-card"><TxTable tx={tx} onVoucher={onVoucher} onEdit={onEdit} remove={remove}/></div></section>
}

function Owners({owners,onEdit,onAdd}){return <section className="page"><div className="toolbar"><div><span className="eyebrow">MASTER DATA</span><h3>Pemilik dan kapasitas kendaraan</h3></div><button className="primary" data-testid="add-owner-button" onClick={onAdd}><Plus size={15}/> Tambah pemilik</button></div><div className="owner-grid">{owners.map(o=><div className="owner-card" key={o.id} data-testid={`owner-card-${o.id}`}><div className="owner-icon"><Users size={18}/></div><div><h3>{o.name} {!o.active&&<span className="status">nonaktif</span>}</h3><p>{o.vehicle_type}</p></div><strong>{o.capacity_kg.toLocaleString('id-ID')}<small> Kg maks.</small></strong><button className="icon" title="Edit" data-testid={`edit-owner-${o.id}`} onClick={()=>onEdit(o)}><Pencil size={15}/></button></div>)}</div><div className="notice"><CheckCircle2 size={18}/><div><b>Aturan operasional aktif</b><p>Gross tidak boleh melewati kapasitas kendaraan. Tare kosong otomatis dihitung 0 Kg. Petani yang sama diberi jeda minimal 1 jam 45 menit antar pengiriman.</p></div></div></section>}

function OwnerForm({initial,onClose,refresh}){
 const [f,setF]=useState(initial||{name:'',vehicle_type:'Pick Up',capacity_kg:1300,active:true});
 const save=async e=>{e.preventDefault();try{await api.post('/api/owners',{...f,capacity_kg:+f.capacity_kg});toast.success('Master pemilik tersimpan');onClose();refresh()}catch(e){toast.error(err(e))}};
 return <Backdrop onClose={onClose}><form className="modal" onSubmit={save} data-testid="owner-form"><button type="button" className="close" onClick={onClose}><X/></button><span className="eyebrow green">MASTER ARMADA</span><h2>{initial?'Ubah pemilik':'Pemilik baru'}</h2><label>Nama pemilik / petani<input data-testid="owner-name-input" required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Jenis kendaraan<input data-testid="owner-vehicle-input" required value={f.vehicle_type} onChange={e=>setF({...f,vehicle_type:e.target.value})}/></label><label>Kapasitas maksimum (Kg)<input data-testid="owner-capacity-input" type="number" min="1" required value={f.capacity_kg} onChange={e=>setF({...f,capacity_kg:e.target.value})}/></label><label className="check-row"><input type="checkbox" data-testid="owner-active-checkbox" checked={f.active} onChange={e=>setF({...f,active:e.target.checked})}/> Aktif dipakai generator & input</label><button className="primary wide" data-testid="save-owner-button"><CheckCircle2 size={16}/> Simpan pemilik</button></form></Backdrop>
}

function Admin({users,approve,reject}){return <section className="page"><div className="toolbar"><div><span className="eyebrow">ACCESS CONTROL</span><h3>Approval akun operator</h3></div><span className="tag gold">{users.filter(u=>u.status==='pending').length} menunggu</span></div><div className="section-card"><div className="table-wrap"><table><thead><tr><th>Nama</th><th>Email</th><th>Role</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.name}</b></td><td>{u.email}</td><td>{u.role}</td><td><span className={`status ${u.status}`}>{u.status}</span></td><td><div className="row-actions">{u.status==='pending'&&<button className="small-primary" data-testid={`approve-user-${u.id}`} onClick={()=>approve(u.id)}>Setujui</button>}{u.role!=='admin'&&<button className="icon danger" title="Tolak / hapus akun" data-testid={`reject-user-${u.id}`} onClick={()=>reject(u.id)}><UserX size={15}/></button>}</div></td></tr>)}</tbody></table></div></div></section>}

function Backdrop({onClose,children}){
 useEffect(()=>{const h=e=>e.key==='Escape'&&onClose();window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[onClose]);
 return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}>{children}</div>
}

function BatchManager({batches,isAdmin,onClose,createBatch,activateBatch,deleteBatch}){
 const [month,setMonth]=useState(new Date().toISOString().slice(0,7));
 return <Backdrop onClose={onClose}><div className="modal" data-testid="batch-manager-modal"><button type="button" className="close" onClick={onClose}><X/></button><span className="eyebrow green">PERIODE BULANAN</span><h2>Kelola batch</h2><p className="muted">Buat batch untuk bulan tertentu (mis. Agustus), aktifkan batch tujuan input/generator, atau hapus batch beserta transaksinya.</p><div className="batch-create"><label>Bulan batch baru<input data-testid="new-batch-month-input" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><button className="primary" data-testid="create-batch-button" onClick={()=>createBatch(month)}><Plus size={15}/> Buat & aktifkan</button></div><div className="batch-list">{batches.map(b=><div className="batch-row" key={b.id} data-testid={`batch-row-${b.id}`}><div><b>{b.label}</b><small>{b.id}{b.active?' · AKTIF':''}</small></div><div className="row-actions">{!b.active&&<button className="small-primary" data-testid={`activate-batch-${b.id}`} onClick={()=>activateBatch(b.id)}>Aktifkan</button>}{isAdmin&&<button className="icon danger" title="Hapus batch" data-testid={`delete-batch-${b.id}`} onClick={()=>deleteBatch(b)}><Trash2 size={15}/></button>}</div></div>)}</div></div></Backdrop>
}

function Generate({onClose,submit}){return <Backdrop onClose={onClose}><form className="modal" onSubmit={submit} data-testid="generator-form"><button type="button" className="close" onClick={onClose}><X/></button><span className="eyebrow green">GENERATOR REALISTIS</span><h2>Bangun target tepat</h2><p className="muted">Slot natural 07:00–16:00, jeda petani ≥1j45m, tanpa pemilik berurutan. Jika target tidak terkejar, sistem otomatis memakai jam istirahat; bila tetap tidak cukup, tidak ada data yang disimpan.</p><label>Dari tanggal<input name="start" data-testid="generator-start-input" type="date" required defaultValue="2026-07-31"/></label><label>Sampai tanggal<input name="end" data-testid="generator-end-input" type="date" required defaultValue="2026-08-01"/></label><label>Target netto (Kg)<input name="target" data-testid="generator-target-input" type="number" min="1" required defaultValue="6450"/></label><label>Harga beli / Kg<input name="price" data-testid="generator-price-input" type="number" min="1" required defaultValue="3000"/></label><button className="primary wide" data-testid="run-generator-button"><RefreshCw size={16}/> Generate & simpan</button></form></Backdrop>}

function TxForm({batch,owners,initial,onClose,refresh}){
 const [f,setF]=useState(initial?{...initial,tare_kg:initial.tare_kg??''}:{date:new Date().toISOString().slice(0,10),arrival_time:'07:15:20',exit_time:'07:42:18',owner_id:owners[0]?.id||'',gross_kg:1000,tare_kg:'',price_per_kg:3000,note:''});
 const save=async e=>{e.preventDefault();const o=owners.find(x=>x.id===f.owner_id);try{await api.post('/api/transactions',{id:f.id,transaction_code:f.transaction_code,batch_id:f.batch_id||batch,date:f.date,arrival_time:f.arrival_time,exit_time:f.exit_time,owner_id:f.owner_id,owner_name:o.name,vehicle_type:o.vehicle_type,gross_kg:+f.gross_kg,tare_kg:f.tare_kg===''?null:+f.tare_kg,price_per_kg:+f.price_per_kg,note:f.note||''});toast.success(initial?'Transaksi diperbarui':'Penerimaan tersimpan');onClose();refresh()}catch(e){toast.error(err(e))}};
 return <Backdrop onClose={onClose}><form className="modal" onSubmit={save} data-testid="transaction-form"><button type="button" className="close" onClick={onClose}><X/></button><span className="eyebrow green">{initial?'KOREKSI TIMBANGAN':'CATAT TIMBANGAN'}</span><h2>{initial?`Edit ${initial.transaction_code}`:'Penerimaan baru'}</h2><div className="form-grid"><label>Tanggal<input data-testid="tx-date-input" type="date" required value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></label><label>Pemilik<select data-testid="tx-owner-select" value={f.owner_id} onChange={e=>setF({...f,owner_id:e.target.value})}>{owners.map(o=><option key={o.id} value={o.id}>{o.name} · {o.vehicle_type}</option>)}</select></label><label>Jam terima<input data-testid="tx-arrival-input" type="text" pattern="[0-9]{2}:[0-9]{2}:[0-9]{2}" required value={f.arrival_time} onChange={e=>setF({...f,arrival_time:e.target.value})}/></label><label>Jam keluar<input data-testid="tx-exit-input" type="text" pattern="[0-9]{2}:[0-9]{2}:[0-9]{2}" required value={f.exit_time} onChange={e=>setF({...f,exit_time:e.target.value})}/></label><label>Gross (Kg)<input data-testid="tx-gross-input" type="number" required value={f.gross_kg} onChange={e=>setF({...f,gross_kg:e.target.value})}/></label><label>Tare (Kg) · boleh kosong<input data-testid="tx-tare-input" type="number" value={f.tare_kg} onChange={e=>setF({...f,tare_kg:e.target.value})}/></label><label>Harga / Kg<input data-testid="tx-price-input" type="number" required value={f.price_per_kg} onChange={e=>setF({...f,price_per_kg:e.target.value})}/></label><label>Catatan<input data-testid="tx-note-input" type="text" value={f.note||''} onChange={e=>setF({...f,note:e.target.value})}/></label></div><button className="primary wide" data-testid="save-transaction-button"><CheckCircle2 size={16}/> {initial?'Simpan perubahan':'Simpan transaksi'}</button></form></Backdrop>
}

function Voucher({tx,onClose}){return <Backdrop onClose={onClose}><div className="voucher-modal"><button className="close" onClick={onClose}><X/></button><div className="voucher" data-testid="voucher-preview"><div className="voucher-head"><div><span className="eyebrow green">PT SAWIT JAYA MAKMUR</span><h2>JEMBATAN TIMBANG</h2><p>Periode {tx.date.slice(0,7)} · Lampiran penerimaan buah</p></div><b className="voucher-code">{tx.transaction_code}</b></div><div className="voucher-grid"><div><small>TANGGAL BUAH DITERIMA</small><b>{dateId(tx.date)}</b></div><div><small>PEMILIK / PETANI</small><b>{tx.owner_name}</b></div><div><small>KENDARAAN</small><b>{tx.vehicle_type}</b></div><div><small>JAM TERIMA → KELUAR</small><b>{tx.arrival_time} → {tx.exit_time}</b></div></div><div className="weights"><div><small>GROSS</small><b>{tx.gross_kg.toLocaleString('id-ID')} Kg</b></div><div><small>TARE</small><b>{tx.tare_kg==null?'—':`${tx.tare_kg.toLocaleString('id-ID')} Kg`}</b></div><div className="net"><small>NETTO</small><b>{tx.netto_kg.toLocaleString('id-ID')} Kg</b><span>{tx.netto_ton.toFixed(2)} Ton</span></div></div><div className="voucher-grid"><div><small>HARGA / KG</small><b>{money(tx.price_per_kg)}</b></div><div><small>TOTAL PEMBELIAN</small><b>{money(tx.total_amount)}</b></div></div><div className="signatures"><div>Petani / Pemilik buah<div>........................</div></div><div>Operator timbang PT SJM<div>........................</div></div></div></div><button className="primary wide" data-testid="print-voucher-button" onClick={()=>window.print()}><Printer size={16}/> Print preview / cetak</button></div></Backdrop>}
